### ISSUE TITLE
AttributeError when running "Extract Growth Rates" command

### ISSUE THREAD

**Issue by mgboebinger** [jsbangsund/crystal-growth-rate-analysis#6]
Hello,

I have been trying to use this code to get some growth rates of particles I have, but I have been getting the attribute error message (copied below) when I use the "Extract Growth Rates" command after picking the directions of interest. Oddly enough though I have gotten the growth rates a couple times, but I did not do anything differently so I am not sure how to go about fixing my issues. If it helps the first time I had this error was when I attempted to change the calibration settings to match my images, but I am doubtful that caused the problem as I now have gotten the same error after reinstalling the environment and running the original GrowthRateAnalyzer.py file.

Thanks for your help!

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\2g5\Anaconda3\envs\image\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "GrowthRateAnalyzer.py", line 1057, in extract_growth_rates
    self.distances = np.zeros((len(self.lines),len(self.times)))
AttributeError: 'GrowthRateAnalyzer' object has no attribute 'lines'

**Comment by jsbangsund** [comment]
This may be an order-of-operations issue---I should improve documentation around this and put in exception handling to catch these errors, but can you confirm the order of steps that you use?

The general workflow is:
 - Click "Open Files" and select timeseries images
 - Click "Pick Crop" and select a zoomed portion of the image (if you would like, you can use the whole image as well)
 - Click "Pick Directions" and click a point in the center of your particle/crystal and at least one point outside of your particle. The way this is set up to measure growth along multiple directions assuming all lines start at the same center point.
 - Click "Get Directions"
- Click "Extract Growth Rate"

If you use these steps, what happens?

**Comment by mgboebinger** [comment]
Wow as easy as that! Yeah, this order seems to have fixed my error. I was working off what appeared to be the order of operations in the gif and did not notice the "Get Directions" command in the sequence that did not include the subtraction. In hindsight, this makes sense though, but thank you for your help!

**Comment by jsbangsund** [comment]
Yeah, sorry I should have made that clearer! This program is definitely a little ad hoc. When I get a free minute I might make error handling more clear on this.

**Comment by jsbangsund** [comment]
This should be fixed in commit bfb015c
I made it so the Get Directions function is automatically run when "Extract Growth Rates" is pressed.
